name: example
description: "ShowPlatformDatePicker example"

publish_to: 'none' 

version: 1.0.5+0

environment:
  sdk: '>=3.9.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  show_platform_date_picker:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

