name: show_platform_date_picker
description: Mnimalist wrapper around the showDatePicker and CupertinoDatePicker methods.
version: 0.0.6
homepage: https://responsivehelp.com
repository: https://github.com/tinoper/show_platform_date_picker/tree/main/show_platform_date_picker
issue_tracker: https://github.com/tinoper/show_platform_date_picker/issues

environment:
  sdk: '>=3.9.0'
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

